# Start from PHP 8.1 + Apache
FROM php:7.4-apache

# System dependencies
RUN apt-get update && apt-get install -y \
    git zip unzip libzip-dev libpng-dev \
 && docker-php-ext-install pdo_mysql zip gd \
 && a2enmod rewrite

# Set working directory
WORKDIR /var/www/html

# Install Composer
COPY --from=composer:2.4 /usr/bin/composer /usr/bin/composer

# Copy source and install PHP deps
COPY . .
RUN composer install --no-dev --optimize-autoloader

# Set folder permissions
RUN chown -R www-data:www-data storage bootstrap/cache \
 && chmod -R 775 storage bootstrap/cache

EXPOSE 80
CMD ["apache2-foreground"]
