#version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"                  # Host 8000 → Container 80 (Apache)
    volumes:
      - ./:/var/www/html/public:rw
      - ./vhost.conf:/etc/apache2/sites-enabled/000-default.conf:ro          # Your Laravel code in the container
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: http://localhost:8000'

      DB_CONNECTION: mysql
      DB_HOST: db                  # ← Point at the MySQL service
      DB_PORT: 3306
      DB_DATABASE: eparty2
      DB_USERNAME: root
      DB_PASSWORD: ''              # Empty root password

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"                # Expose MySQL on localhost:3306
    environment:
      MYSQL_DATABASE: eparty2
      MYSQL_ROOT_PASSWORD: ''      # Empty root password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
