
services:
  app: 
    image: khawa1zme/projsoftapp:latest
    ports:
      - "8182:80"                  # Host 8000 → Container 80 (Apache)
    volumes:
      - ./:/var/www/html

  db:
    image: mysql
    restart: always
 #   ports:
 #     - "3307:3306"             # Expose MySQL on localhost:3306
    environment:
      MYSQL_DATABASE: eparty2
      MYSQL_ROOT_PASSWORD: ''      # Empty root password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Allow empty root password
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "3308:80"            # host 8080 → container 80
    environment:
      PMA_HOST: db           # service name of MySQL container
      PMA_PORT: 3306
      PMA_ALLOW_NO_PASSWORD: 'yes'
