apiVersion: apps/v1
kind: Deployment
metadata:
  name: projsoftapp-deployment
  labels:
    app: projsoftapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projsoftapp
  template:
    metadata:
      labels:
        app: projsoftapp
    spec:
      containers:
        - name: projsoftapp-container
          image: khawa1zme/projsoftapp:v1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: projsoftapp-service
spec:
  type: NodePort  
  selector:
    app: projsoftapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
